lamp:
  nginx:
    ip: 127.0.0.1      # 正式环境需要将该ip设置成nginx对应的 公网ip
    port: 10000
  cache:
    type: REDIS
  redis:
    ip: 127.0.0.1
    port: 16379
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy
    database: 0
  rabbitmq:
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: zuihou
    password: zuihou
  oracle: &db-oracle
    db-type: oracle
    validation-query: SELECT 'x' FROM DUAL
    filters: stat,wall,slf4j       # druid不支持使用p6spy打印日志，所以采用druid 的 slf4j 过滤器来打印可执行日志
    username: 'lamp_column_plus'
    password: 'lamp_column_plus'
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.26.3.67:1521:helowin
    owner: ''
    p6spy: false
  database:
     <<: *db-oracle
     multiTenantType: COLUMN
     p6spy: false


spring:
  datasource:
    druid:
      <<: *db-oracle
      filter:
        slf4j:
          enabled: true     # 使用slf4j打印可执行日志时，改成true
          statement-executable-sql-log-enable: true
