lamp:
  nginx:
    ip: 127.0.0.1      # 正式环境需要将该ip设置成nginx对应的 公网ip
    port: 10000
  cache:
    type: REDIS
  redis:
    ip: 127.0.0.1
    port: 16379
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy
    database: 0
  rabbitmq:
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: zuihou
    password: zuihou
  oracle: &db-oracle
    db-type: oracle
    validation-query: SELECT 'x' FROM DUAL
    filters: stat,wall,slf4j       # druid不支持使用p6spy打印日志，所以采用druid 的 slf4j 过滤器来打印可执行日志
    username: 'lamp_defaults'
    password: 'lamp_defaults'
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.26.3.67:1521:helowin
    owner: ''
  mysql: &db-mysql
    db-type: mysql
    validation-query: SELECT 'x'
    filters: stat,wall
    username: 'root'
    password: 'root'
    owner: ''
    # 生产使用原生驱动，开发使用p6spy驱动打印日志
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lamp_defaults?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
  sqlserver: &db-sqlserver
    username: 'sa'
    password: '1234@abcd'
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # url: jdbc:sqlserver://172.26.3.67:1433;DatabaseName=lamp_defaults
    url: jdbc:sqlserver://117.187.194.249:1433;DatabaseName=lamp_defaults
    db-type: sqlserver
    validation-query: SELECT 'x'
    filters: stat,wall
    owner: 'dbo'
  database:
#    <<: *db-sqlserver
    <<: *db-mysql
    # <<: *db-oracle


spring:
  datasource:
    druid:
      <<: *db-mysql
